apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app  : nginx
    env  : prod
    owner: kot
spec:
  replicas: 2
  selector:
    matchLabels:
      project: nginx
  template:
    metadata:
      labels:
        project: nginx
    spec:
      containers:
        - name : nginx
          image: "kotara2905/websaite1:{{image_tag}}"
          ports:
          - containerPort: 80
          - containerPort: 443
      imagePullSecrets:
      - name: regcred


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaling
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  