apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{namespace}}
  labels:
    app  : nginx
    env  : prod
    owner: kot
spec:
  replicas: 2
  selector:
    matchLabels:
      project: nginx
  template:
    metadata:
      labels:
        project: nginx
    spec:
      containers:
        - name : nginx
          image: "kotara2905/websaite1:{{image_tag}}"
          ports:
          - containerPort: 80
          - containerPort: 443
      imagePullSecrets:
      - name: regcred1


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaling
  namespace: {{namespace}}
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: nginx
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

  