apiVersion: v1
kind: Service
metadata:
  name: tomcat 
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat
  # namespace: {{namespace}}
  labels:
    app: tomcat 
    # branch: {{prefix}}
  annotations:
    # kubernetes.io/tls-acme: "false"
    # kubernetes.io/ingress.class: "ingress-nginx"
    # nginx.ingress.kubernetes.io/server-alias: "k8s.dcserver.ru"
    # nginx.ingress.kubernetes.io/client-body-buffer-size: "40M"
    # nginx.ingress.kubernetes.io/proxy-body-size: "40M"
spec:
  rules:
    - host: cat.adv-it.net
      http:
      paths:
        - backend:
           serviceName: tomcat
           servicePort: 8080