apiVersion: v1
kind: Service
metadata:
  name: tomcat 
spec:
  selector:
      app.kubernetes.io/name: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 12815

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat
  # namespace: {{namespace}}
  labels:
    app: tomcat
    # branch: {{prefix}}
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "false"
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.dcserver.ru
      http:
        paths:
          - backend:
              service:
                name: tomcat
                port:
                  number: 12815
            path: /
            pathType: Prefix



# kubernetes.io/tls-acme: "false"
    # kubernetes.io/ingress.class: "tomcat"
    # nginx.ingress.kubernetes.io/server-alias: "k8s.dcserver.ru"
    # nginx.ingress.kubernetes.io/client-body-buffer-size: "40M"
    # nginx.ingress.kubernetes.io/proxy-body-size: "40M"