apiVersion: v1
kind: Service
metadata:
  name: tomcat 
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
  - host: k8s.dcserver.ru
    http:
      paths:
        - backend:
           serviceName: tomcat
           servicePort: 80